### ISSUE TITLE
Issue with ш

### ISSUE THREAD

**Issue by xfra35** [Gavin-TC/Cyrillatin#3]
Hi,

Thanks for this extension, it looks promising!

I think there's a little typo in the [phonics variable](https://github.com/Gavin-TC/Cyrillatin/blob/rewrite/src/background.js#L34).

ш should convert to "sh" and not "sha".

Otherwise, Masha converts to Маш.

**Comment by Gavin-TC** [comment]
That's definitely a typo! Thanks for spotting that! Not sure how I messed that up. I'll change it now.
